server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
spring:
  application:
    name: travel-web
  main:
    allow-bean-definition-overriding: true
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: localhost:9301
      cluster-name: elasticsearch
redis:
  host: localhost
  port: 6379
  jedis:
  pool:
    max-idle: 300
    max-active: 600
    max-wait: 300


