server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
spring:
  application:
    name: travel-server
  data:

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.101.6:3306/travel?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong
    username: root
    password: 1996920
mybatis:
  mapper-locations: /mapper/*.xml
